/* Generated By:JavaCC: Do not edit this line. grammarConstants.java */
package lab1;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface grammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DIGIT = 5;
  /** RegularExpression Id. */
  int LETTER = 6;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<DIGIT>",
    "<LETTER>",
    "\"(\"",
    "\"+\"",
    "\"-\"",
    "\")\"",
    "\"ff\"",
    "\"tt\"",
    "\"==\"",
    "\"!\"",
    "\"^\"",
    "\"skip\"",
    "\":=\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"while\"",
    "\"do\"",
    "\";\"",
  };

}
